// Generated by gencpp from file lla2enu/DistanceCalculator.msg
// DO NOT EDIT!


#ifndef LLA2ENU_MESSAGE_DISTANCECALCULATOR_H
#define LLA2ENU_MESSAGE_DISTANCECALCULATOR_H

#include <ros/service_traits.h>


#include <lla2enu/DistanceCalculatorRequest.h>
#include <lla2enu/DistanceCalculatorResponse.h>


namespace lla2enu
{

struct DistanceCalculator
{

typedef DistanceCalculatorRequest Request;
typedef DistanceCalculatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DistanceCalculator
} // namespace lla2enu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lla2enu::DistanceCalculator > {
  static const char* value()
  {
    return "4e22589e822a5a44dc1faf02bd3b965d";
  }

  static const char* value(const ::lla2enu::DistanceCalculator&) { return value(); }
};

template<>
struct DataType< ::lla2enu::DistanceCalculator > {
  static const char* value()
  {
    return "lla2enu/DistanceCalculator";
  }

  static const char* value(const ::lla2enu::DistanceCalculator&) { return value(); }
};


// service_traits::MD5Sum< ::lla2enu::DistanceCalculatorRequest> should match
// service_traits::MD5Sum< ::lla2enu::DistanceCalculator >
template<>
struct MD5Sum< ::lla2enu::DistanceCalculatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lla2enu::DistanceCalculator >::value();
  }
  static const char* value(const ::lla2enu::DistanceCalculatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lla2enu::DistanceCalculatorRequest> should match
// service_traits::DataType< ::lla2enu::DistanceCalculator >
template<>
struct DataType< ::lla2enu::DistanceCalculatorRequest>
{
  static const char* value()
  {
    return DataType< ::lla2enu::DistanceCalculator >::value();
  }
  static const char* value(const ::lla2enu::DistanceCalculatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lla2enu::DistanceCalculatorResponse> should match
// service_traits::MD5Sum< ::lla2enu::DistanceCalculator >
template<>
struct MD5Sum< ::lla2enu::DistanceCalculatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lla2enu::DistanceCalculator >::value();
  }
  static const char* value(const ::lla2enu::DistanceCalculatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lla2enu::DistanceCalculatorResponse> should match
// service_traits::DataType< ::lla2enu::DistanceCalculator >
template<>
struct DataType< ::lla2enu::DistanceCalculatorResponse>
{
  static const char* value()
  {
    return DataType< ::lla2enu::DistanceCalculator >::value();
  }
  static const char* value(const ::lla2enu::DistanceCalculatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLA2ENU_MESSAGE_DISTANCECALCULATOR_H
