// Generated by gencpp from file lla2enu/DistanceCalculatorRequest.msg
// DO NOT EDIT!


#ifndef LLA2ENU_MESSAGE_DISTANCECALCULATORREQUEST_H
#define LLA2ENU_MESSAGE_DISTANCECALCULATORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lla2enu
{
template <class ContainerAllocator>
struct DistanceCalculatorRequest_
{
  typedef DistanceCalculatorRequest_<ContainerAllocator> Type;

  DistanceCalculatorRequest_()
    : x(0.0)
    , y(0.0)
    , x_obs(0.0)
    , y_obs(0.0)  {
    }
  DistanceCalculatorRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , x_obs(0.0)
    , y_obs(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _x_obs_type;
  _x_obs_type x_obs;

   typedef double _y_obs_type;
  _y_obs_type y_obs;





  typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceCalculatorRequest_

typedef ::lla2enu::DistanceCalculatorRequest_<std::allocator<void> > DistanceCalculatorRequest;

typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorRequest > DistanceCalculatorRequestPtr;
typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorRequest const> DistanceCalculatorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator1> & lhs, const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.x_obs == rhs.x_obs &&
    lhs.y_obs == rhs.y_obs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator1> & lhs, const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lla2enu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52673d80d545cd3a373c40523ebbeaf8";
  }

  static const char* value(const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52673d80d545cd3aULL;
  static const uint64_t static_value2 = 0x373c40523ebbeaf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lla2enu/DistanceCalculatorRequest";
  }

  static const char* value(const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 x_obs\n"
"float64 y_obs\n"
;
  }

  static const char* value(const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.x_obs);
      stream.next(m.y_obs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceCalculatorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lla2enu::DistanceCalculatorRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "x_obs: ";
    Printer<double>::stream(s, indent + "  ", v.x_obs);
    s << indent << "y_obs: ";
    Printer<double>::stream(s, indent + "  ", v.y_obs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLA2ENU_MESSAGE_DISTANCECALCULATORREQUEST_H
