// Generated by gencpp from file lla2enu/DistanceCalculatorResponse.msg
// DO NOT EDIT!


#ifndef LLA2ENU_MESSAGE_DISTANCECALCULATORRESPONSE_H
#define LLA2ENU_MESSAGE_DISTANCECALCULATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lla2enu
{
template <class ContainerAllocator>
struct DistanceCalculatorResponse_
{
  typedef DistanceCalculatorResponse_<ContainerAllocator> Type;

  DistanceCalculatorResponse_()
    : distance(0.0)  {
    }
  DistanceCalculatorResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DistanceCalculatorResponse_

typedef ::lla2enu::DistanceCalculatorResponse_<std::allocator<void> > DistanceCalculatorResponse;

typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorResponse > DistanceCalculatorResponsePtr;
typedef boost::shared_ptr< ::lla2enu::DistanceCalculatorResponse const> DistanceCalculatorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator1> & lhs, const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator1> & lhs, const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lla2enu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lla2enu/DistanceCalculatorResponse";
  }

  static const char* value(const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
"\n"
;
  }

  static const char* value(const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DistanceCalculatorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lla2enu::DistanceCalculatorResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLA2ENU_MESSAGE_DISTANCECALCULATORRESPONSE_H
